# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sorulur' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
		pod 'Alamofire'
	pod 'Firebase/Analytics'
    #   pod 'XCGLogger'
pod 'RealmSwift'
pod 'ActionKit'
pod 'SnapKit'
pod 'DLRadioButton'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage'
pod 'CocoaDebug', :configurations => ['Debug']
pod 'SkeletonView'
  # Pods for sorulur

  target 'sorulurTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sorulurUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'sorulurWatch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sorulurWatch

end

target 'sorulurWatch Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sorulurWatch Extension

end
